[versions]

vKotlin = "2.0.20"
vMavenPublish = "0.30.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "vKotlin" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "vKotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vMavenPublish" }